const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGOUT = "LOGOUT";
export { LOGIN_ERROR, LOGIN_REQUEST, LOGOUT, LOGIN_SUCCESS };
