const REGISRTATION_REQUEST = "REGISRTATION_REQUEST";
const REGISRTATION_SUCCESS = "REGISRTATION_SUCCESS";
const REGISRTATION_ERROR = "REGISRTATION_ERROR";
export { REGISRTATION_ERROR, REGISRTATION_REQUEST, REGISRTATION_SUCCESS };